---
# tasks file for httpd
- name: Install Apache server
  yum:
    name: httpd
    state: present
- name: copy file with permissions
  template:
    src: files/index.html
    dest: /var/www/html
    owner: root
    group: root
    mode: '0644'
...
